env := ./venv
rundir := ./droid
pip := $(env)/bin/pip
python := ../venv/bin/python
build_deps := $(rundir)/requirements.txt


run: $(clean) $(env)
	@cd $(rundir) && nice --19 $(python) start.py;

$(env):
	python3 -m venv $@ && $(pip) install -r $(build_deps)

clean:
	@rm -rf **/__pycache__
